[private]
build:
  cargo build --release

[windows]
ship: build
  cp target/release/custom_ffi.dll lua/custom_ffi.dll

[linux]
ship: build
  cp target/release/libcustom_ffi.so lua/custom_ffi.so

[macos]
ship: build
  cp target/release/libcustom_ffi.dylib lua/custom_ffi.so


clean:
  cargo clean
